version: "3.9"

services:
  nginx:
    image: nginx:1.23.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    container_name: nginx-proxy
    depends_on:
      - app
      - mariadb
      - redis
    networks:
      - backend
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    profiles:
      - app
    env_file:
      - .env
    depends_on:
      - mariadb
      - redis
    command:
      - bash
      - -c
      - |
        npm run --prefix backend build
        npm run --prefix backend start:prod
        #/app/wait-for-it.sh db:5432 -t 10
    networks:
      - backend
    volumes:
      - ./:/src
    # healthcheck:
    #   interval: 10s
    #   retries: 12

  mariadb:
    image: mariadb:10.8.2
    ports:
      - "3306:3306"
    profiles:
      - app
      - infra-only
    env_file:
      - .env
    networks:
      - backend
    restart: on-failure

  redis:
    image: bitnami/redis:6.2
    ports:
      - "6379:6379"
    env_file:
      - .env
    profiles:
      - app
      - infra-only
    networks:
      - backend
    #deploy:
    #  replicas: 2
    #  update_config:
    #    parallelism: 2
    #    delay: 10s
    #  restart_policy:
    #    condition: on-failure

networks:
  backend:

volumes:
  mysql-data:
  redis-data: