version: "3.9"

services:
  nginx:
    image: nginx:1.23.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    container_name: nginx-proxy
    depends_on:
      - app
    networks:
      - backend
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    env_file:
      - .env
    command:
      - bash
      - -c
      - |
        npm run --prefix backend build
        npm run --prefix backend start:prod
    networks:
      - backend
    healthcheck:
      interval: 10s
      retries: 10
    restart: on-failure
    volumes:
      - app-data

  mariadb:
    image: mariadb:10.8.2
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - backend
    profiles:
      - infra
    restart: on-failure
    volumes:
      - mysql-data

  redis:
    image: bitnami/redis:6.2
    ports:
      - "6379:6379"
    env_file:
      - .env
    networks:
      - backend
    profiles:
      - infra
    restart: on-failure
    volumes:
      - redis-data
    #deploy:
    #  replicas: 2
    #  update_config:
    #    parallelism: 2
    #    delay: 10s

networks:
  backend:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
  app-data: