version: "3.9"

services:
  nginx:
    image: nginx:1.23.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    container_name: nginx-proxy
    depends_on:
      - app
      - mariadb
      - redis
    networks:
      - backend
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    profiles:
      - app
    env_file:
      - .env
    depends_on:
      - mariadb
      - redis
    command:
      - bash
      - -c
      - |
        while ! nc -z mariadb 3306; do sleep 3; done
        while ! nc -z redis 6379; do sleep 3; done
        npm run --prefix backend build
        npm run --prefix backend start:prod
    networks:
      - backend
    volumes:
      - ./:/src
    healthcheck:
      interval: 10s
      retries: 10
    restart: on-failure

  mariadb:
    image: mariadb:10.8.2
    ports:
      - "3306:3306"
    profiles:
      - app
      - infra-only
    env_file:
      - .env
    networks:
      - backend
    restart: on-failure

  redis:
    image: bitnami/redis:6.2
    ports:
      - "6379:6379"
    env_file:
      - .env
    profiles:
      - app
      - infra-only
    networks:
      - backend
    restart: on-failure
    #deploy:
    #  replicas: 2
    #  update_config:
    #    parallelism: 2
    #    delay: 10s

networks:
  backend:
    driver: bridge

volumes:
  mysql-data:
  redis-data: