version: "3.9"

services:
  mariadb:
    image: mariadb:10.8.2
    container_name: app-mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - backend
    restart: on-failure
    volumes:
      - mysql-data:/mysql-data

  redis:
    image: redis:7.0.9-alpine
    container_name: app-redis
    ports:
      - "6379:6379"
    env_file:
      - .env
    networks:
      - backend
    restart: on-failure
    volumes:
      - redis-data:/data

networks:
  backend:
    driver: bridge

volumes:
  mysql-data:
  redis-data: