version: "3.9"

services:
  mariadb:
    image: mariadb:10.8.2
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - backend
    restart: on-failure

  redis:
    image: bitnami/redis:6.2
    ports:
      - "6379:6379"
    env_file:
      - .env
    networks:
      - backend
    restart: on-failure

networks:
  backend:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
  app-data: