version: "3.9"

services:
  redis:
    image: redis:7.0.9-alpine
    container_name: redis
    ports:
      - "6379:6379"
    env_file:
      - .env
    restart: on-failure
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    volumes:
      - ./redis:/data
    networks:
      - default
  mariadb:
    image: mariadb:10.11.2-jammy
    container_name: mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env
    restart: on-failure
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - default

networks:
  default: